In [19]:
from pycaret.classification import *
from pycaret.classification import setup
import pandas as pd

In [20]:
data = pd.read_csv(r"C:\Users\NT550-052\OneDrive\바탕 화면\ASAC\프로젝트\ML\web_crawling\CGW\modeling\onlyonehot\onlyonehot.csv",sep=";")
data.drop(columns="Unnamed: 0",inplace=True)
data

,appid,24_Hour_Peak,All_time_peak,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,genre,...,short,simulation,softwaretraining,sports,strategy,tutorial,utilities,videoproduction,violent,webpublishing
0,294100,20930,60742,12492,1401,5368,921,34.99,34.99,"Indie, Simulation, Strategy",...,0,1,0,0,1,0,0,0,0,0
1,960090,13428,53891,4018,277,1532,62,13.99,13.99,Strategy,...,0,0,0,0,1,0,0,0,0,0
2,504230,1234,4148,1316,310,370,582,19.99,19.99,"Action, Adventure, Indie",...,0,0,0,0,0,0,0,0,0,0
3,588650,4553,14880,1841,183,868,213,14.99,24.99,"Action, Adventure, Indie",...,0,0,0,0,0,0,0,0,0,0
4,264710,4205,50876,1943,313,941,277,29.99,29.99,"Adventure, Indie",...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46247,1995280,0,0,0,0,0,0,14.99,14.99,"Adventure, Indie",...,0,0,0,0,0,0,0,0,0,0
46248,2098860,0,0,0,0,0,0,9.99,9.99,"Adventure, Casual",...,0,0,0,0,0,0,0,0,0,0
46249,2154770,814,1176,0,0,0,0,0.00,0.00,N,...,0,0,0,0,0,0,0,0,0,0
46250,1915410,0,1,0,0,0,0,2.99,2.99,"Action, Indie",...,0,0,0,0,0,0,0,0,0,0
46251,1563130,4,97,0,0,0,0,29.99,29.99,"Simulation, Strategy",...,0,1,0,0,1,0,0,0,0,0

In [21]:
data["months_after_release"] = data["days_after_release"]//30

In [22]:
data.columns

Index(['appid', '24_Hour_Peak', 'All_time_peak', 'average_forever',
       'average_2weeks', 'median_forever', 'median_2weeks', 'price',
       'initialprice', 'genre', 'num_lang', 'required_age', 'is_free',
       'controller_support', 'dlc', 'metacritic_tf', 'windows', 'mac', 'linux',
       'platforms_num', 'achievements', 'days_after_release',
       'months_after_release', 'Review', '360v', 'accounting', 'action',
       'actiongames', 'adventure', 'animation', 'audioproduction', 'casual',
       'design', 'documentary', 'earlyaccess', 'education', 'episodic',
       'freetoplay', 'gamedevelopment', 'gore', 'illustration', 'indie',
       'massivelymultiplayer', 'modeling', 'movie', 'nudity', 'photoediting',
       'racing', 'rpg', 'sexualcontent', 'short', 'simulation',
       'softwaretraining', 'sports', 'strategy', 'tutorial', 'utilities',
       'videoproduction', 'violent', 'webpublishing'],
      dtype='object')

In [23]:
data["Review"].value_counts()

Negative    26833
Positive    19419
Name: Review, dtype: int64

In [24]:
tag_path = r"C:\Users\NT550-052\OneDrive\바탕 화면\ASAC\프로젝트\ML\web_crawling\merge_dataset\tag_merge.csv"
tag_df = pd.read_csv(tag_path)
tag_df

,appid,Cartoon,Hunting,Time Management,Zombies,Isometric,Chess,Musou,Experimental,3D,...,360 Video,Linear,Grid-Based Movement,FMV,Lemmings,Tile-Matching,Indie,Arcade,Atmospheric,Cats
0,294100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1223.0,0.0,0.0,0.0
1,960090,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,337.0,...,0.0,0.0,0.0,0.0,0.0,0.0,161.0,0.0,0.0,0.0
2,504230,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,887.0,0.0,320.0,0.0
3,588650,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1003.0,0.0,3360.0,0.0
4,264710,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1420.0,0.0,2618.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46718,1995280,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46719,2098860,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,322.0,0.0
46720,2154770,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46721,1915410,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,21.0,0.0,0.0,0.0
46722,1563130,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,433.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,412.0,0.0

In [25]:
tag_df.iloc[:,1:] = tag_df.iloc[:,1:].astype("bool")
tag_df.iloc[:,1:] = tag_df.iloc[:,1:].astype("int")
data = pd.merge(data,tag_df,how="inner",left_on="appid",right_on="appid")

In [26]:
data

,appid,24_Hour_Peak,All_time_peak,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,genre,...,360 Video,Linear,Grid-Based Movement,FMV,Lemmings,Tile-Matching,Indie,Arcade,Atmospheric,Cats
0,294100,20930,60742,12492,1401,5368,921,34.99,34.99,"Indie, Simulation, Strategy",...,0,0,0,0,0,0,1,0,0,0
1,960090,13428,53891,4018,277,1532,62,13.99,13.99,Strategy,...,0,0,0,0,0,0,1,0,0,0
2,504230,1234,4148,1316,310,370,582,19.99,19.99,"Action, Adventure, Indie",...,0,0,0,0,0,0,1,0,1,0
3,588650,4553,14880,1841,183,868,213,14.99,24.99,"Action, Adventure, Indie",...,0,0,0,0,0,0,1,0,1,0
4,264710,4205,50876,1943,313,941,277,29.99,29.99,"Adventure, Indie",...,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46247,1995280,0,0,0,0,0,0,14.99,14.99,"Adventure, Indie",...,0,0,0,0,0,0,0,0,0,0
46248,2098860,0,0,0,0,0,0,9.99,9.99,"Adventure, Casual",...,0,0,0,0,0,0,0,0,1,0
46249,2154770,814,1176,0,0,0,0,0.00,0.00,N,...,0,0,0,0,0,0,0,0,0,0
46250,1915410,0,1,0,0,0,0,2.99,2.99,"Action, Indie",...,0,0,0,0,0,0,1,0,0,0
46251,1563130,4,97,0,0,0,0,29.99,29.99,"Simulation, Strategy",...,0,0,0,0,0,0,0,0,1,0

In [27]:
data.drop(columns=["genre","appid"],inplace=True)

In [28]:
data

,24_Hour_Peak,All_time_peak,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,num_lang,required_age,...,360 Video,Linear,Grid-Based Movement,FMV,Lemmings,Tile-Matching,Indie,Arcade,Atmospheric,Cats
0,20930,60742,12492,1401,5368,921,34.99,34.99,35,0.0,...,0,0,0,0,0,0,1,0,0,0
1,13428,53891,4018,277,1532,62,13.99,13.99,24,0.0,...,0,0,0,0,0,0,1,0,0,0
2,1234,4148,1316,310,370,582,19.99,19.99,14,0.0,...,0,0,0,0,0,0,1,0,1,0
3,4553,14880,1841,183,868,213,14.99,24.99,21,0.0,...,0,0,0,0,0,0,1,0,1,0
4,4205,50876,1943,313,941,277,29.99,29.99,38,0.0,...,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46247,0,0,0,0,0,0,14.99,14.99,4,0.0,...,0,0,0,0,0,0,0,0,0,0
46248,0,0,0,0,0,0,9.99,9.99,1,0.0,...,0,0,0,0,0,0,0,0,1,0
46249,814,1176,0,0,0,0,0.00,0.00,0,0.0,...,0,0,0,0,0,0,0,0,0,0
46250,0,1,0,0,0,0,2.99,2.99,1,0.0,...,0,0,0,0,0,0,1,0,0,0
46251,4,97,0,0,0,0,29.99,29.99,16,0.0,...,0,0,0,0,0,0,0,0,1,0

In [29]:
X = data.drop(columns="Review")
y = data["Review"]

In [30]:
from sklearn.model_selection import train_test_split 



X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 1234, # 옵션, 재현성을 위함 
    stratify = y # 옵션 : 비율 나눌 때 비율 유지할지 말지 
)

In [31]:
X_train["Review"] = y_train.to_list()

In [32]:
X_train

,24_Hour_Peak,All_time_peak,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,num_lang,required_age,...,Linear,Grid-Based Movement,FMV,Lemmings,Tile-Matching,Indie,Arcade,Atmospheric,Cats,Review
4834,0,28,28,0,49,0,0.00,0.00,1,0.0,...,0,0,0,0,0,1,0,0,0,Negative
12340,0,0,0,0,0,0,4.99,4.99,1,0.0,...,0,0,0,0,0,0,0,0,0,Negative
42383,0,0,0,0,0,0,0.00,0.00,0,0.0,...,0,0,0,0,0,0,0,0,0,Positive
3639,0,215,215,0,215,0,24.99,24.99,2,0.0,...,0,0,0,0,0,1,0,1,0,Negative
912,0,0,0,0,0,0,0.00,0.00,1,0.0,...,0,0,0,0,0,1,0,0,0,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36650,0,42,0,0,0,0,0.00,0.00,0,0.0,...,0,0,0,0,0,0,0,0,0,Positive
18130,0,367,367,0,367,0,18.99,18.99,1,0.0,...,0,0,0,0,0,1,0,0,0,Positive
8308,45,311,139,1,17,1,0.99,0.99,1,0.0,...,0,0,0,0,0,1,0,0,0,Positive
29813,1,51,0,0,0,0,0.00,0.00,1,0.0,...,0,0,0,0,0,0,0,0,0,Negative
45961,0,0,0,0,0,0,14.99,14.99,1,0.0,...,0,0,0,0,0,0,0,0,0,Negative

In [33]:
X_test

,24_Hour_Peak,All_time_peak,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,num_lang,required_age,...,360 Video,Linear,Grid-Based Movement,FMV,Lemmings,Tile-Matching,Indie,Arcade,Atmospheric,Cats
40317,0,0,0,0,0,0,3.49,34.99,1,0.0,...,0,0,0,0,0,0,1,0,0,0
5060,0,0,0,0,0,0,7.99,7.99,1,0.0,...,0,0,0,0,0,0,1,1,0,0
21348,0,1,0,0,0,0,4.99,4.99,1,0.0,...,0,0,0,0,0,0,0,1,0,0
17508,0,7,0,0,0,0,2.99,4.99,2,0.0,...,0,0,0,0,0,0,1,0,0,0
37599,0,0,0,0,0,0,4.99,4.99,1,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10138,2,46,0,0,0,0,19.99,19.99,3,0.0,...,0,0,0,0,0,0,0,0,0,0
17544,0,0,0,0,0,0,0.00,0.00,1,0.0,...,0,0,0,0,0,0,1,0,0,0
5190,1,221,0,0,0,0,49.99,49.99,4,12.0,...,0,1,0,0,0,0,0,0,0,0
4578,0,0,0,0,0,0,7.99,7.99,1,0.0,...,0,0,0,0,0,0,1,0,0,0
42524,1,120,0,0,0,0,0.00,0.00,0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [34]:
exp = ClassificationExperiment()

In [35]:
exp.setup(X_train, target='Review', session_id=123, fold_strategy="stratifiedkfold",fix_imbalance=True)

In [36]:
best = exp.compare_models(n_select = 5)

Initiated  . . . . . . . . . . . . . . . . . .              11:14:23
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

In [42]:
best

[LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
                importance_type='split', learning_rate=0.1, max_depth=-1,
                min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
                n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
                random_state=123, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
                subsample=1.0, subsample_for_bin=200000, subsample_freq=0),
 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                        criterion='gini', max_depth=None, max_features='sqrt',
                        max_leaf_nodes=None, max_samples=None,
                        min_impurity_decrease=0.0, min_samples_leaf=1,
                        min_samples_split=2, min_weight_fraction_leaf=0.0,
                        n_estimators=100, n_jobs=-1, oob_score=False,
                        random_state=123, verbose=0, warm_start=False),
 GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                            learning_rate=0.1, loss='log_loss', max_depth=3,
                            max_features=None, max_leaf_nodes=None,
                            min_impurity_decrease=0.0, min_samples_leaf=1,
                            min_samples_split=2, min_weight_fraction_leaf=0.0,
                            n_estimators=100, n_iter_no_change=None,
                            random_state=123, subsample=1.0, tol=0.0001,
                            validation_fraction=0.1, verbose=0,
                            warm_start=False),
 AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                    estimator=None, learning_rate=1.0, n_estimators=50,
                    random_state=123),
 ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                      criterion='gini', max_depth=None, max_features='sqrt',
                      max_leaf_nodes=None, max_samples=None,
                      min_impurity_decrease=0.0, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=-1, oob_score=False,
                      random_state=123, verbose=0, warm_start=False)]

In [44]:
exp.pull()

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC,TT (Sec)
lightgbm,Light Gradient Boosting Machine,0.7414,0.8035,0.6125,0.7287,0.6654,0.4573,0.4620,1.390
rf,Random Forest Classifier,0.7391,0.7962,0.5991,0.7311,0.6585,0.4508,0.4567,3.685
gbc,Gradient Boosting Classifier,0.7287,0.7859,0.5785,0.7204,0.6416,0.4275,0.4343,7.357
ada,Ada Boost Classifier,0.7152,0.7702,0.5917,0.6871,0.6356,0.4040,0.4073,3.058
et,Extra Trees Classifier,0.7121,0.7621,0.5744,0.6884,0.6262,0.3952,0.3995,6.473
ridge,Ridge Classifier,0.6632,0.0000,0.6354,0.5923,0.6130,0.3156,0.3162,0.831
lda,Linear Discriminant Analysis,0.6631,0.7126,0.6351,0.5923,0.6129,0.3154,0.3160,2.131
dt,Decision Tree Classifier,0.6515,0.6436,0.5882,0.5845,0.5863,0.2853,0.2853,1.274
lr,Logistic Regression,0.6477,0.6913,0.6010,0.5773,0.5888,0.2809,0.2811,13.240
knn,K Neighbors Classifier,0.6344,0.6675,0.5966,0.5607,0.5780,0.2560,0.2564,2.060
nb,Naive Bayes,0.5934,0.6762,0.0535,0.7102,0.0992,0.0430,0.1053,0.727
dummy,Dummy Classifier,0.5802,0.5000,0.0000,0.0000,0.0000,0.0000,0.0000,0.642
qda,Quadratic Discriminant Analysis,0.5766,0.5286,0.2123,0.5539,0.2405,0.0576,0.0820,1.692
svm,SVM - Linear Kernel,0.4951,0.0000,0.6527,0.5355,0.4868,0.0464,0.0347,0.788

In [38]:
best

[LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
                importance_type='split', learning_rate=0.1, max_depth=-1,
                min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
                n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
                random_state=123, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
                subsample=1.0, subsample_for_bin=200000, subsample_freq=0),
 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                        criterion='gini', max_depth=None, max_features='sqrt',
                        max_leaf_nodes=None, max_samples=None,
                        min_impurity_decrease=0.0, min_samples_leaf=1,
                        min_samples_split=2, min_weight_fraction_leaf=0.0,
                        n_estimators=100, n_jobs=-1, oob_score=False,
                        random_state=123, verbose=0, warm_start=False),
 GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                            learning_rate=0.1, loss='log_loss', max_depth=3,
                            max_features=None, max_leaf_nodes=None,
                            min_impurity_decrease=0.0, min_samples_leaf=1,
                            min_samples_split=2, min_weight_fraction_leaf=0.0,
                            n_estimators=100, n_iter_no_change=None,
                            random_state=123, subsample=1.0, tol=0.0001,
                            validation_fraction=0.1, verbose=0,
                            warm_start=False),
 AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                    estimator=None, learning_rate=1.0, n_estimators=50,
                    random_state=123),
 ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                      criterion='gini', max_depth=None, max_features='sqrt',
                      max_leaf_nodes=None, max_samples=None,
                      min_impurity_decrease=0.0, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=-1, oob_score=False,
                      random_state=123, verbose=0, warm_start=False)]

In [39]:
prediction = exp.predict_model(best, data = X_test)

AttributeError: 'list' object has no attribute 'predict'

In [ ]:
prediction

,24_Hour_Peak,All_time_peak,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,num_lang,required_age,...,Grid-Based Movement,FMV,Lemmings,Tile-Matching,Indie,Arcade,Atmospheric,Cats,prediction_label,prediction_score
40317,0,0,0,0,0,0,3.490000,34.990002,1,0.0,...,0,0,0,0,1,0,0,0,Positive,0.8621
5060,0,0,0,0,0,0,7.990000,7.990000,1,0.0,...,0,0,0,0,1,1,0,0,Negative,0.6981
21348,0,1,0,0,0,0,4.990000,4.990000,1,0.0,...,0,0,0,0,0,1,0,0,Negative,0.7892
17508,0,7,0,0,0,0,2.990000,4.990000,2,0.0,...,0,0,0,0,1,0,0,0,Negative,0.5997
37599,0,0,0,0,0,0,4.990000,4.990000,1,0.0,...,0,0,0,0,0,0,0,0,Negative,0.7270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10138,2,46,0,0,0,0,19.990000,19.990000,3,0.0,...,0,0,0,0,0,0,0,0,Negative,0.6334
17544,0,0,0,0,0,0,0.000000,0.000000,1,0.0,...,0,0,0,0,1,0,0,0,Positive,0.5905
5190,1,221,0,0,0,0,49.990002,49.990002,4,12.0,...,0,0,0,0,0,0,0,0,Positive,0.7072
4578,0,0,0,0,0,0,7.990000,7.990000,1,0.0,...,0,0,0,0,1,0,0,0,Negative,0.8984
42524,1,120,0,0,0,0,0.000000,0.000000,0,0.0,...,0,0,0,0,0,0,0,0,Positive,0.7438

In [ ]:
b=best.predict(X_test).astype("bool")

In [ ]:
c=y_test.replace("Positive",1)
c=c.replace("Negative",0)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(c,b))

              precision    recall  f1-score   support

           0       0.75      0.85      0.79      5367
           1       0.74      0.61      0.67      3884

    accuracy                           0.75      9251
   macro avg       0.75      0.73      0.73      9251
weighted avg       0.75      0.75      0.74      9251

In [ ]:
tune = exp.tune_model(best, search_library = 'optuna',n_iter = 30)

Initiated  . . . . . . . . . . . . . . . . . .              20:52:44
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

[I 2023-05-24 20:52:45,066] Searching the best hyperparameters using 25900 samples...
[I 2023-05-24 21:07:36,945] Finished hyperparemeter search!

In [ ]:
# 66.8%

In [ ]:
tune

LGBMClassifier(bagging_fraction=0.6717010340302931, bagging_freq=1,
               boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               feature_fraction=0.8954632787661868, importance_type='split',
               learning_rate=0.0364611479281597, max_depth=-1,
               min_child_samples=36, min_child_weight=0.001,
               min_split_gain=0.28908713340023673, n_estimators=181, n_jobs=-1,
               num_leaves=82, objective=None, random_state=123,
               reg_alpha=5.746360899277371e-06,
               reg_lambda=0.0006500418806757982, silent='warn', subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)

In [ ]:
b=tune.predict(X_test).astype("bool")

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(c,b))

              precision    recall  f1-score   support

           0       0.76      0.84      0.80      5367
           1       0.74      0.63      0.68      3884

    accuracy                           0.75      9251
   macro avg       0.75      0.73      0.74      9251
weighted avg       0.75      0.75      0.75      9251