In [1]:
from pycaret.classification import *
from pycaret.classification import setup
import pandas as pd

In [2]:
data = pd.read_csv(r"C:\Users\NT550-052\OneDrive\바탕 화면\ASAC\프로젝트\ML\web_crawling\CGW\modeling\clstandoh\clusterandoh.csv",sep=";")
data.drop(columns="Unnamed: 0",inplace=True)
data

,appid,24_Hour_Peak,All_time_peak,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,genre,...,strategy,tutorial,utilities,videoproduction,violent,webpublishing,c0,c1,c2,c3
0,294100,20930,60742,12492,1401,5368,921,34.99,34.99,"Indie, Simulation, Strategy",...,1,0,0,0,0,0,0,0,0,3
1,960090,13428,53891,4018,277,1532,62,13.99,13.99,Strategy,...,1,0,0,0,0,0,0,0,0,1
2,504230,1234,4148,1316,310,370,582,19.99,19.99,"Action, Adventure, Indie",...,0,0,0,0,0,0,0,0,0,3
3,588650,4553,14880,1841,183,868,213,14.99,24.99,"Action, Adventure, Indie",...,0,0,0,0,0,0,0,0,0,3
4,264710,4205,50876,1943,313,941,277,29.99,29.99,"Adventure, Indie",...,0,0,0,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46247,1995280,0,0,0,0,0,0,14.99,14.99,"Adventure, Indie",...,0,0,0,0,0,0,0,0,0,2
46248,2098860,0,0,0,0,0,0,9.99,9.99,"Adventure, Casual",...,0,0,0,0,0,0,0,0,0,2
46249,2154770,814,1176,0,0,0,0,0.00,0.00,N,...,0,0,0,0,0,0,0,0,1,0
46250,1915410,0,1,0,0,0,0,2.99,2.99,"Action, Indie",...,0,0,0,0,0,0,0,0,0,2
46251,1563130,4,97,0,0,0,0,29.99,29.99,"Simulation, Strategy",...,1,0,0,0,0,0,0,0,0,2

In [3]:
tag_path = r"C:\Users\NT550-052\OneDrive\바탕 화면\ASAC\프로젝트\ML\web_crawling\merge_dataset\tag_merge.csv"
tag_df = pd.read_csv(tag_path)
tag_df

,appid,Cartoon,Hunting,Time Management,Zombies,Isometric,Chess,Musou,Experimental,3D,...,360 Video,Linear,Grid-Based Movement,FMV,Lemmings,Tile-Matching,Indie,Arcade,Atmospheric,Cats
0,294100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1223.0,0.0,0.0,0.0
1,960090,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,337.0,...,0.0,0.0,0.0,0.0,0.0,0.0,161.0,0.0,0.0,0.0
2,504230,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,887.0,0.0,320.0,0.0
3,588650,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1003.0,0.0,3360.0,0.0
4,264710,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1420.0,0.0,2618.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46718,1995280,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46719,2098860,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,322.0,0.0
46720,2154770,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46721,1915410,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,21.0,0.0,0.0,0.0
46722,1563130,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,433.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,412.0,0.0

In [4]:
tag_df.iloc[:,1:] = tag_df.iloc[:,1:].astype("bool")
tag_df.iloc[:,1:] = tag_df.iloc[:,1:].astype("int")
data = pd.merge(data,tag_df,how="inner",left_on="appid",right_on="appid")

In [5]:
data

,appid,24_Hour_Peak,All_time_peak,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,genre,...,360 Video,Linear,Grid-Based Movement,FMV,Lemmings,Tile-Matching,Indie,Arcade,Atmospheric,Cats
0,294100,20930,60742,12492,1401,5368,921,34.99,34.99,"Indie, Simulation, Strategy",...,0,0,0,0,0,0,1,0,0,0
1,960090,13428,53891,4018,277,1532,62,13.99,13.99,Strategy,...,0,0,0,0,0,0,1,0,0,0
2,504230,1234,4148,1316,310,370,582,19.99,19.99,"Action, Adventure, Indie",...,0,0,0,0,0,0,1,0,1,0
3,588650,4553,14880,1841,183,868,213,14.99,24.99,"Action, Adventure, Indie",...,0,0,0,0,0,0,1,0,1,0
4,264710,4205,50876,1943,313,941,277,29.99,29.99,"Adventure, Indie",...,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46247,1995280,0,0,0,0,0,0,14.99,14.99,"Adventure, Indie",...,0,0,0,0,0,0,0,0,0,0
46248,2098860,0,0,0,0,0,0,9.99,9.99,"Adventure, Casual",...,0,0,0,0,0,0,0,0,1,0
46249,2154770,814,1176,0,0,0,0,0.00,0.00,N,...,0,0,0,0,0,0,0,0,0,0
46250,1915410,0,1,0,0,0,0,2.99,2.99,"Action, Indie",...,0,0,0,0,0,0,1,0,0,0
46251,1563130,4,97,0,0,0,0,29.99,29.99,"Simulation, Strategy",...,0,0,0,0,0,0,0,0,1,0

In [6]:
data.drop(columns=["genre","appid"],inplace=True)

In [7]:
model = setup(data, target='Review', session_id=123, fold_strategy="stratifiedkfold")

In [8]:
exp = ClassificationExperiment()

In [9]:
exp.setup(data, target='Review', session_id=123, fold_strategy="stratifiedkfold")

In [10]:
best = compare_models()

In [11]:
pull()

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC,TT (Sec)
lightgbm,Light Gradient Boosting Machine,0.6700,0.8271,0.6700,0.6474,0.6367,0.4467,0.4564,1.268
rf,Random Forest Classifier,0.6615,0.8138,0.6615,0.6311,0.6252,0.4321,0.4434,4.267
gbc,Gradient Boosting Classifier,0.6551,0.8140,0.6551,0.6324,0.6128,0.4170,0.4303,25.141
et,Extra Trees Classifier,0.6377,0.7834,0.6377,0.6071,0.6095,0.3964,0.4029,6.877
ada,Ada Boost Classifier,0.6312,0.7452,0.6312,0.5989,0.5951,0.3802,0.3902,2.941
ridge,Ridge Classifier,0.5997,0.0000,0.5997,0.5708,0.5572,0.3207,0.3315,0.489
lda,Linear Discriminant Analysis,0.5953,0.7458,0.5953,0.5690,0.5678,0.3261,0.3326,1.983
lr,Logistic Regression,0.5856,0.6713,0.5856,0.5853,0.5248,0.2920,0.3245,18.029
knn,K Neighbors Classifier,0.5580,0.6872,0.5580,0.5235,0.5254,0.2656,0.2767,2.135
dt,Decision Tree Classifier,0.5526,0.6542,0.5526,0.5525,0.5525,0.2925,0.2926,1.154
nb,Naive Bayes,0.4304,0.7126,0.4304,0.5942,0.3036,0.1036,0.1627,0.507
dummy,Dummy Classifier,0.4198,0.5000,0.4198,0.1763,0.2483,0.0000,0.0000,0.316
svm,SVM - Linear Kernel,0.4050,0.0000,0.4050,0.5519,0.3655,0.1333,0.1753,2.009
qda,Quadratic Discriminant Analysis,0.1894,0.5488,0.1894,0.5386,0.2201,0.0422,0.0584,1.634

In [12]:
best

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=123, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [14]:
tune = tune_model(best, search_library = 'optuna',n_iter = 20)

Initiated  . . . . . . . . . . . . . . . . . .              17:01:56
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

[I 2023-05-24 17:01:56,785] Searching the best hyperparameters using 32376 samples...
[I 2023-05-24 17:13:07,215] Finished hyperparemeter search!

In [ ]:
# 67.2%