genre로 컬럼 구성해서 장르별 positive,negative,mixed,imdifference의 평균 정보가 담긴 df 만들기

In [20]:
import pandas as pd

In [21]:
path = r"C:\Users\NT550-052\OneDrive\바탕 화면\ASAC\프로젝트\ML\web_crawling\CGW\modeling\onlyonehot\onlyonehot.csv"
data = pd.read_csv(path, sep=";")
data.drop(columns="Unnamed: 0",inplace=True)

In [22]:
data.columns

Index(['appid', '24_Hour_Peak', 'All_time_peak', 'average_forever',
       'average_2weeks', 'median_forever', 'median_2weeks', 'price',
       'initialprice', 'genre', 'num_lang', 'required_age', 'is_free',
       'controller_support', 'dlc', 'metacritic_tf', 'windows', 'mac', 'linux',
       'platforms_num', 'achievements', 'days_after_release',
       'months_after_release', 'Review', '360v', 'accounting', 'action',
       'actiongames', 'adventure', 'animation', 'audioproduction', 'casual',
       'design', 'documentary', 'earlyaccess', 'education', 'episodic',
       'freetoplay', 'gamedevelopment', 'gore', 'illustration', 'indie',
       'massivelymultiplayer', 'modeling', 'movie', 'nudity', 'photoediting',
       'racing', 'rpg', 'sexualcontent', 'short', 'simulation',
       'softwaretraining', 'sports', 'strategy', 'tutorial', 'utilities',
       'videoproduction', 'violent', 'webpublishing'],
      dtype='object')

In [23]:
data.columns[1:-36]

Index(['24_Hour_Peak', 'All_time_peak', 'average_forever', 'average_2weeks',
       'median_forever', 'median_2weeks', 'price', 'initialprice', 'genre',
       'num_lang', 'required_age', 'is_free', 'controller_support', 'dlc',
       'metacritic_tf', 'windows', 'mac', 'linux', 'platforms_num',
       'achievements', 'days_after_release', 'months_after_release', 'Review'],
      dtype='object')

In [24]:
# data.drop(columns=['appid', '24_Hour_Peak', 'All_time_peak', 'average_forever',
#        'average_2weeks', 'median_forever', 'median_2weeks', 'price',
#        'initialprice', 'genre', 'num_lang', 'required_age', 'is_free',
#        'controller_support', 'dlc', 'metacritic_tf', 'windows', 'mac', 'linux',
#        'platforms_num', 'achievements', 'days_after_release'],inplace=True)

In [25]:
data

,appid,24_Hour_Peak,All_time_peak,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,genre,...,short,simulation,softwaretraining,sports,strategy,tutorial,utilities,videoproduction,violent,webpublishing
0,294100,20930,60742,12492,1401,5368,921,34.99,34.99,"Indie, Simulation, Strategy",...,0,1,0,0,1,0,0,0,0,0
1,960090,13428,53891,4018,277,1532,62,13.99,13.99,Strategy,...,0,0,0,0,1,0,0,0,0,0
2,504230,1234,4148,1316,310,370,582,19.99,19.99,"Action, Adventure, Indie",...,0,0,0,0,0,0,0,0,0,0
3,588650,4553,14880,1841,183,868,213,14.99,24.99,"Action, Adventure, Indie",...,0,0,0,0,0,0,0,0,0,0
4,264710,4205,50876,1943,313,941,277,29.99,29.99,"Adventure, Indie",...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46247,1995280,0,0,0,0,0,0,14.99,14.99,"Adventure, Indie",...,0,0,0,0,0,0,0,0,0,0
46248,2098860,0,0,0,0,0,0,9.99,9.99,"Adventure, Casual",...,0,0,0,0,0,0,0,0,0,0
46249,2154770,814,1176,0,0,0,0,0.00,0.00,N,...,0,0,0,0,0,0,0,0,0,0
46250,1915410,0,1,0,0,0,0,2.99,2.99,"Action, Indie",...,0,0,0,0,0,0,0,0,0,0
46251,1563130,4,97,0,0,0,0,29.99,29.99,"Simulation, Strategy",...,0,1,0,0,1,0,0,0,0,0

In [26]:
data["Review"].value_counts()

Negative    26833
Positive    19419
Name: Review, dtype: int64

In [27]:
tmp = data[(data["sports"]==1) & (data["Review"]=="Positive")].iloc[:,1:-36].describe().loc["mean",:]
# tmp.loc["mean",:].to_list()
tmp

24_Hour_Peak             196.562130
All_time_peak           1615.797633
average_forever          359.067456
average_2weeks            13.265089
median_forever           296.778698
median_2weeks             13.334911
price                      9.671006
initialprice              12.837882
num_lang                   7.208284
required_age               0.053254
is_free                    0.182249
controller_support         0.306509
dlc                        1.020118
metacritic_tf              0.057988
windows                    0.992899
mac                        0.223669
linux                      0.118343
platforms_num              1.334911
achievements              29.268639
days_after_release       970.591716
months_after_release      31.867456
Name: mean, dtype: float64

In [28]:
data.columns[-36:]

Index(['360v', 'accounting', 'action', 'actiongames', 'adventure', 'animation',
       'audioproduction', 'casual', 'design', 'documentary', 'earlyaccess',
       'education', 'episodic', 'freetoplay', 'gamedevelopment', 'gore',
       'illustration', 'indie', 'massivelymultiplayer', 'modeling', 'movie',
       'nudity', 'photoediting', 'racing', 'rpg', 'sexualcontent', 'short',
       'simulation', 'softwaretraining', 'sports', 'strategy', 'tutorial',
       'utilities', 'videoproduction', 'violent', 'webpublishing'],
      dtype='object')

In [29]:
data.drop(columns=["genre","mac","linux","windows","is_free"],inplace=True)

In [30]:
final = pd.DataFrame(columns=['24_Hour_Peak', 'All_time_peak', 'average_forever',
       'average_2weeks', 'median_forever', 'median_2weeks', 'price',
       'initialprice', 'num_lang', 'required_age', 
       'controller_support', 'dlc', 'metacritic_tf', 
       'platforms_num', 'achievements', 'days_after_release','months_after_release'])

In [31]:
final

Empty DataFrame
Columns: [24_Hour_Peak, All_time_peak, average_forever, average_2weeks, median_forever, median_2weeks, price, initialprice, num_lang, required_age, controller_support, dlc, metacritic_tf, platforms_num, achievements, days_after_release, months_after_release]
Index: []

In [32]:
len(final.columns) == len(data[(data["sports"]==1) & (data["Review"]=="Positive")].iloc[:,1:-37].columns)

True

In [33]:
data[(data["360v"]==1) & (data["Review"]=="Positive")].iloc[:,1:-37]

Empty DataFrame
Columns: [24_Hour_Peak, All_time_peak, average_forever, average_2weeks, median_forever, median_2weeks, price, initialprice, num_lang, required_age, controller_support, dlc, metacritic_tf, platforms_num, achievements, days_after_release, months_after_release]
Index: []

In [34]:
data[data["360v"]==1].describe()

,appid,24_Hour_Peak,All_time_peak,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,num_lang,...,short,simulation,softwaretraining,sports,strategy,tutorial,utilities,videoproduction,violent,webpublishing
count,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.00,1.00,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
mean,1434230.0,0.0,0.0,0.0,0.0,0.0,0.0,4.99,4.99,38.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1434230.0,0.0,0.0,0.0,0.0,0.0,0.0,4.99,4.99,38.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0
25%,1434230.0,0.0,0.0,0.0,0.0,0.0,0.0,4.99,4.99,38.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0
50%,1434230.0,0.0,0.0,0.0,0.0,0.0,0.0,4.99,4.99,38.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0
75%,1434230.0,0.0,0.0,0.0,0.0,0.0,0.0,4.99,4.99,38.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0
max,1434230.0,0.0,0.0,0.0,0.0,0.0,0.0,4.99,4.99,38.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0

In [35]:
gen = data.columns[-36:].to_list()
for elem in gen:
    final.loc[elem+" Positive"] = data[(data[elem]==1) & (data["Review"]=="Positive")].iloc[:,1:-37].describe().loc["mean",:].to_list()
    final.loc[elem+" Negative"] = data[(data[elem]==1) & (data["Review"]=="Negative")].iloc[:,1:-37].describe().loc["mean",:].to_list()

In [36]:
final

,24_Hour_Peak,All_time_peak,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,num_lang,required_age,controller_support,dlc,metacritic_tf,platforms_num,achievements,days_after_release,months_after_release
360v Positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
360v Negative,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,4.990000,4.990000,38.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,947.000000,31.000000
accounting Positive,0.000000,109.000000,49.000000,0.00000,73.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1900.000000,63.000000
accounting Negative,0.000000,0.666667,0.000000,0.00000,0.000000,0.000000,3.323333,3.323333,13.333333,0.000000,0.333333,0.666667,0.000000,1.000000,0.333333,1154.666667,38.000000
action Positive,148.020706,1702.654418,185.580782,17.03762,148.636045,18.937154,9.387332,10.185900,7.144794,0.267717,0.407699,0.877078,0.073053,1.307378,26.214348,987.808836,32.447944
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
videoproduction Negative,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,8.490000,8.490000,20.500000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,905.500000,29.500000
violent Positive,0.238095,33.190476,24.047619,0.00000,28.095238,0.000000,5.200000,5.371429,2.142857,0.000000,0.190476,0.000000,0.000000,1.333333,7.285714,1836.952381,60.666667
violent Negative,0.000000,0.852273,0.295455,0.00000,0.306818,0.000000,6.558750,6.989886,1.852273,0.000000,0.079545,0.034091,0.022727,1.159091,3.147727,1846.215909,61.022727
webpublishing Positive,79.333333,494.333333,41.666667,0.00000,48.333333,0.000000,0.330000,0.330000,17.666667,0.000000,0.000000,0.000000,0.000000,1.333333,33.000000,1544.333333,51.000000
webpublishing Negative,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,4.990000,4.990000,38.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,947.000000,31.000000

In [ ]:
final.to_csv(r"C:\Users\NT550-052\OneDrive\바탕 화면\ASAC\프로젝트\ML\web_crawling\CGW\report\report.csv",sep=";")