In [1]:
from pycaret.classification import *
import pandas as pd

In [2]:
data = pd.read_csv(r"C:\Users\NT550-052\OneDrive\바탕 화면\ASAC\프로젝트\ML\web_crawling\CGW\modeling\onlyonehot\onlyonehot.csv",sep=";")
data.drop(columns="Unnamed: 0",inplace=True)
data

,appid,24_Hour_Peak,All_time_peak,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,genre,...,short,simulation,softwaretraining,sports,strategy,tutorial,utilities,videoproduction,violent,webpublishing
0,294100,20930,60742,12492,1401,5368,921,34.99,34.99,"Indie, Simulation, Strategy",...,0,1,0,0,1,0,0,0,0,0
1,960090,13428,53891,4018,277,1532,62,13.99,13.99,Strategy,...,0,0,0,0,1,0,0,0,0,0
2,504230,1234,4148,1316,310,370,582,19.99,19.99,"Action, Adventure, Indie",...,0,0,0,0,0,0,0,0,0,0
3,588650,4553,14880,1841,183,868,213,14.99,24.99,"Action, Adventure, Indie",...,0,0,0,0,0,0,0,0,0,0
4,264710,4205,50876,1943,313,941,277,29.99,29.99,"Adventure, Indie",...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46247,1995280,0,0,0,0,0,0,14.99,14.99,"Adventure, Indie",...,0,0,0,0,0,0,0,0,0,0
46248,2098860,0,0,0,0,0,0,9.99,9.99,"Adventure, Casual",...,0,0,0,0,0,0,0,0,0,0
46249,2154770,814,1176,0,0,0,0,0.00,0.00,N,...,0,0,0,0,0,0,0,0,0,0
46250,1915410,0,1,0,0,0,0,2.99,2.99,"Action, Indie",...,0,0,0,0,0,0,0,0,0,0
46251,1563130,4,97,0,0,0,0,29.99,29.99,"Simulation, Strategy",...,0,1,0,0,1,0,0,0,0,0

In [3]:
# tag 데이터 불러오기 
tag_path = r"C:\Users\NT550-052\OneDrive\바탕 화면\ASAC\프로젝트\ML\web_crawling\merge_dataset\tag_merge.csv"
tag_df = pd.read_csv(tag_path)
tag_df

,appid,Cartoon,Hunting,Time Management,Zombies,Isometric,Chess,Musou,Experimental,3D,...,360 Video,Linear,Grid-Based Movement,FMV,Lemmings,Tile-Matching,Indie,Arcade,Atmospheric,Cats
0,294100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1223.0,0.0,0.0,0.0
1,960090,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,337.0,...,0.0,0.0,0.0,0.0,0.0,0.0,161.0,0.0,0.0,0.0
2,504230,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,887.0,0.0,320.0,0.0
3,588650,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1003.0,0.0,3360.0,0.0
4,264710,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1420.0,0.0,2618.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46718,1995280,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46719,2098860,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,322.0,0.0
46720,2154770,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46721,1915410,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,21.0,0.0,0.0,0.0
46722,1563130,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,433.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,412.0,0.0

In [4]:
# tag 데이터 binary 변환 
tag_df.iloc[:,1:] = tag_df.iloc[:,1:].astype("bool")
tag_df.iloc[:,1:] = tag_df.iloc[:,1:].astype("int")

In [ ]:
data = pd.merge(data,tag_df,how="inner",left_on="appid",right_on="appid")

In [5]:
# tag 개수 컬럼 추가 
data["tag_num"] = tag_df.iloc[:,1:].sum(axis=1)

In [7]:
# 모델 학습에 불필요한 컬럼 제거 
data.drop(columns=["genre","appid"],inplace=True)

In [6]:
# 정답지 분리 
X = data.drop(columns="Review")
y = data["Review"]

In [8]:
# train, validation 분리 
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 1234, 
    stratify = y 
)

In [9]:
# train 데이터 조정 : pycaret에서 target으로 y_train 지정을 위함 
X_train["Review"] = y_train.to_list()

In [11]:
# pycaret classification 객체 생성 
exp = ClassificationExperiment()

In [12]:
# setup : stratified kfold, target 불균형 해결을 위한 SMOTE 사용(fix_imbalance) 
exp.setup(X_train, target='Review', session_id=123, fold_strategy="stratifiedkfold",fix_imbalance=True)

In [13]:
# 5개 모델 불러오기 
ada_model = load_model(r'C:\Users\NT550-052\OneDrive\바탕 화면\ASAC\프로젝트\ML\web_crawling\CGW\finaldata\ada_tune_model')
rf_model = load_model(r'C:\Users\NT550-052\OneDrive\바탕 화면\ASAC\프로젝트\ML\web_crawling\CGW\finaldata\rf_tune_model')
lgbm_model = load_model(r'C:\Users\NT550-052\OneDrive\바탕 화면\ASAC\프로젝트\ML\web_crawling\CGW\finaldata\lgbm_tune_model')
et_model = load_model(r'C:\Users\NT550-052\OneDrive\바탕 화면\ASAC\프로젝트\ML\web_crawling\CGW\finaldata\et_tune_model')
gbc_model = load_model(r'C:\Users\NT550-052\OneDrive\바탕 화면\ASAC\프로젝트\ML\web_crawling\CGW\finaldata\gbc_tune_model')

Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded

In [29]:
# soft voting 
tune_blender = exp.blend_models([rf_model,lgbm_model,gbc_model,et_model,ada_model],method="soft")

Initiated  . . . . . . . . . . . . . . . . . .             10:40:51
Status     . . . . . . . . . . . . . . . . . .  Selecting Estimator
Estimator  . . . . . . . . . . . . . . . . . .    Voting Classifier

In [30]:
# prediction
prediction = exp.predict_model(tune_blender, data = X_test)
prediction

,appid,24_Hour_Peak,All_time_peak,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,genre,...,FMV,Lemmings,Tile-Matching,Indie,Arcade,Atmospheric,Cats,tag_num,prediction_label,prediction_score
40317,2064110,0,0,0,0,0,0,3.490000,34.990002,Indie,...,0,0,0,1,0,0,0,7,Positive,0.7199
5060,915930,0,0,0,0,0,0,7.990000,7.990000,Indie,...,0,0,0,1,1,0,0,5,Negative,0.7331
21348,1337070,0,1,0,0,0,0,4.990000,4.990000,"Action, Adventure, Casual, Indie, Simulation, ...",...,0,0,0,0,1,0,0,15,Negative,0.6859
17508,1201930,0,7,0,0,0,0,2.990000,4.990000,"Adventure, Casual, Indie, RPG, Strategy",...,0,0,0,1,0,0,0,6,Negative,0.5962
37599,1894320,0,0,0,0,0,0,4.990000,4.990000,"Casual, Indie, Simulation, Strategy",...,0,0,0,0,0,0,0,19,Negative,0.6401
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10138,1015610,2,46,0,0,0,0,19.990000,19.990000,"Action, Massively Multiplayer, Early Access",...,0,0,0,0,0,0,0,5,Negative,0.7371
17544,1366060,0,0,0,0,0,0,0.000000,0.000000,Casual,...,0,0,0,1,0,0,0,6,Negative,0.6184
5190,525240,1,221,0,0,0,0,49.990002,49.990002,"Action, Adventure, RPG",...,0,0,0,0,0,0,0,6,Positive,0.6032
4578,898440,0,0,0,0,0,0,7.990000,7.990000,"Indie, Simulation, Strategy, Early Access",...,0,0,0,1,0,0,0,3,Negative,0.8031
42524,1662060,1,120,0,0,0,0,0.000000,0.000000,N,...,0,0,0,0,0,0,0,20,Positive,0.7022

In [31]:
b = prediction["prediction_label"]
b

40317    Positive
5060     Negative
21348    Negative
17508    Negative
37599    Negative
           ...
10138    Negative
17544    Negative
5190     Positive
4578     Negative
42524    Positive
Name: prediction_label, Length: 9251, dtype: object

In [33]:
from sklearn.metrics import classification_report
print(classification_report(y_test,b))

              precision    recall  f1-score   support

    Negative       0.76      0.84      0.80      5367
    Positive       0.74      0.63      0.68      3884

    accuracy                           0.75      9251
   macro avg       0.75      0.74      0.74      9251
weighted avg       0.75      0.75      0.75      9251

In [19]:
exp.save_model(tune_blender, "voting_model_file")

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=FastMemory(location=C:\Users\NT550-~1\AppData\Local\Temp\joblib),
          steps=[('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['appid', '24_Hour_Peak',
                                              'All_time_peak', 'average_forever',
                                              'average_2weeks', 'median_forever',
                                              'media...
                                                                                    include=None,
                                                                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+'))),
                                                                ('trained_model',
                                                                 AdaBoostClassifier(algorithm='SAMME.R',
                                                                                    base_estimator='deprecated',
                                                                                    estimator=None,
                                                                                    learning_rate=0.4260735210411416,
                                                                                    n_estimators=131,
                                                                                    random_state=123))],
                                                         verbose=False))],
                                   flatten_transform=True, n_jobs=-1,
                                   verbose=False, voting='soft',
                                   weights=None))],
          verbose=False),
 'voting_model_file.pkl')