In [1]:
### 필요한 모듈 IMPORT
import pandas as pd
from sklearn import preprocessing
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import seaborn as sns

In [7]:
tmp=pd.read_csv(r"C:\Users\moonp\ASAC과정\ASAC_ml_project\EDA\MPW\DATA\onlyonehot_final.csv",sep=";")

In [8]:
col_lst=tmp.columns

In [9]:
tmp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46252 entries, 0 to 46251
Columns: 505 entries, 24_Hour_Peak to tag_num
dtypes: float64(9), int64(495), object(1)
memory usage: 178.2+ MB

In [11]:
le=preprocessing.LabelEncoder()
le.fit(np.array(tmp.Review))
y_true=le.fit_transform(tmp.Review)
print(le.classes_)

['Negative' 'Positive']

In [12]:
y_true

array([1, 1, 1, ..., 0, 0, 0])

In [14]:
tmp_x=tmp[["24_Hour_Peak","All_time_peak","average_forever","average_2weeks","median_forever","median_2weeks",
"price","initialprice","num_lang","required_age","is_free","controller_support","dlc","metacritic_tf",
"windows","mac","linux","platforms_num","achievements","days_after_release","months_after_release"]]
tmp_y=tmp["Review"]

In [15]:
tmp_x

,24_Hour_Peak,All_time_peak,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,num_lang,required_age,...,controller_support,dlc,metacritic_tf,windows,mac,linux,platforms_num,achievements,days_after_release,months_after_release
0,20930,60742,12492,1401,5368,921,34.99,34.99,35,0.0,...,0,6.0,1,1.0,1.0,1.0,3.0,0.0,1675,55
1,13428,53891,4018,277,1532,62,13.99,13.99,24,0.0,...,0,1.0,0,1.0,1.0,0.0,2.0,146.0,1613,53
2,1234,4148,1316,310,370,582,19.99,19.99,14,0.0,...,1,1.0,1,1.0,1.0,1.0,3.0,32.0,1940,64
3,4553,14880,1841,183,868,213,14.99,24.99,21,0.0,...,1,7.0,1,1.0,1.0,1.0,3.0,121.0,1747,58
4,4205,50876,1943,313,941,277,29.99,29.99,38,0.0,...,1,1.0,1,1.0,1.0,0.0,2.0,17.0,1941,64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46247,0,0,0,0,0,0,14.99,14.99,4,0.0,...,0,1.0,0,1.0,0.0,0.0,1.0,0.0,168,5
46248,0,0,0,0,0,0,9.99,9.99,1,0.0,...,0,0.0,0,1.0,0.0,0.0,1.0,0.0,283,9
46249,814,1176,0,0,0,0,0.00,0.00,0,0.0,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,169,5
46250,0,1,0,0,0,0,2.99,2.99,1,0.0,...,0,0.0,0,1.0,0.0,0.0,1.0,0.0,388,12
46251,4,97,0,0,0,0,29.99,29.99,16,0.0,...,0,0.0,0,1.0,0.0,0.0,1.0,35.0,224,7